### ISSUE TITLE
[BE] Create Quiz의 Back-end 작업

### ISSUE THREAD

**Issue by MinSikSon** [ara-official/TriQuiz#21]

**Comment by MinSikSon** [comment]
[설계문서](https://www.notion.so/5ff0d3c82bcf46f6b61821a35fc4e283) 를 보면은..
question 은 quiz_id 를 가지고 있고
question_item 은 question_id 를 가지고 있는 것처럼 보임.

그런데, 각 id 는 auto increment 값이라 database 내에서 관리하고 있는 값인데, question 및 question_item 생성 시점에서 각 quiz_id 및 question_id 값을 어떻게 들고 올 수 있는지??

예를 들어, quiz 열을 새로 생성할 때 quiz_id 값을 리턴 받거나? 한다면 알 수 있을거 같긴 함.

그런데 이게 가능한지?

**Comment by MinSikSon** [comment]
가능함.

**Comment by MinSikSon** [comment]
#18 에서 db 관련 작업을 하고 있었으나, 앞으로는 #21  branch 따서 수행 예정임.

**Comment by Ethan-0218** [comment]
- [x] 칼럼 추가 => likeNum, questionNum, participationNum
- [x] 데이터베이스 설정 파일 별도 관리 
- [x] DTO validation 체크 로직 확인, 에러 메세지, 에러 시 httpStatus 설정 등

**Comment by MinSikSon** [comment]
현재는 DTO-A 에 DTO-B 가 달려 있는 경우에 DTO-B 의 유효성 검사가 안된다고 합니다.
때문에 별도의 방법으로 유효성 검사를 해야합니다.(유효성 검사 코드 작성)

또는 quiz - question - questionItem 을 분리 시켜야 합니다.
